# Generated by Django 4.2.3 on 2023-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_title_txt', models.CharField(max_length=100)),
                ('hackathon_description_txt', models.TextField(blank=True, max_length=2000)),
                ('background_img_path', models.URLField(blank=True)),
                ('hackathon_img_path', models.URLField(blank=True)),
                ('hackathon_submission_mode', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=10)),
                ('hackathon_start_date_txt', models.DateTimeField()),
                ('hackathon_end_date_txt', models.DateTimeField()),
                ('hackathon_reward_prize', models.CharField(max_length=15)),
            ],
        ),
    ]
