# Generated by Django 4.2.3 on 2023-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_API', '0002_alter_hackathon_background_img_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='background_img_path',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_background_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='backgroundImg/'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='Img/'),
        ),
    ]
