# Generated by Django 4.2.3 on 2023-07-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_API', '0003_remove_hackathon_background_img_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_end_date_txt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_start_date_txt',
            field=models.DateTimeField(null=True),
        ),
    ]
